# Generated by Django 4.2.1 on 2023-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='garden',
            field=models.CharField(choices=[('NO', 'No'), ('BAL', 'Balcony'), ('YES', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='house_type',
            field=models.CharField(choices=[('F', 'Flat'), ('H', 'House')], max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='parking',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
    ]
