# Generated by Django 4.2.1 on 2023-05-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_available_from_room_balcony_room_furnished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pets',
        ),
    ]
