# Generated by Django 4.2.1 on 2023-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='residents',
        ),
        migrations.AddField(
            model_name='room',
            name='residents',
            field=models.IntegerField(default=1),
        ),
    ]
