# Generated by Django 4.2.1 on 2023-05-18 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0007_room_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
