# Generated by Django 4.2.1 on 2023-05-21 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0008_alter_room_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=1024)),
                ('zip_code', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
