# Generated by Django 4.2.1 on 2023-05-21 16:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_favourite_roomaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomaddress',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
